# 深入理解Python特性

## 第二章  Python整洁之道

### 2.1  用断言加一层保险

介绍如何在python中使用断言（python内置的assert语句），学习用断言来自动检测python程序中的错误，让程序更可靠且更易于调试。

python的断言是一种调试工具，用来测试某个断言条件。如果断言条件为真，则程序继续正常执行；如果断言条件为假，则会引发AssertionError异常并显示相关的错误信息。

#### 2.1.1 示例：python中的断言

假设需要使用python构建在线商店，为了添加打折优惠券的功能，代码如下

```python
def apply_discount(product, discount):
    price = int(product['price'] * (1.0 - discount))
    assert 0<= price <= product['price']
    return price

shoes = {'name':'Fancy Shoes', 'price': 14900}

apply_discount(shoes, 0.25)

```

这条语句确保在任何情况下，通过该函数计算的折后价不低于0，也不会高于产品原价。

商品中的产品用普通的字典表示。使用整数来表示以分为单位的价格，以此来避免货币的舍入问题。

当尝试使用无效的折扣时，程序会停止并触发一个AssertionError。

从异常栈跟踪信息中还能得知断言验证失败的具体位置。查看异常回溯可以轻松地了解是哪些出了问题。极大地加快了调试工作的速度，并且从长远来看，程序也更易于维护。



#### 2.1.2  为什么不用普通的异常来处理

​         为什么不在前面的示例中使用if语句和异常？

​        要知道，断言是为了告诉开发人员程序中发生了不可恢复的错误。对于可以预期的错误（如未找到相关文件），用户可以予以纠正或者重试，断言并不是为此而生的。

​        断言用于程序**内部自检**，如声明一些代码中不可能出现的条件。如果触发了某个条件，即意味着程序中存在相应的bug。

​        如果程序没有bug，这些断言条件永远不会触发

​    



#### 